Second Ship
Bodhi-Productions/RPG-Racer pull request #5
Opened 2021-01-28 04:03 UTC by Toadboyf

Made a second ship for fun, has a small rotating animation.

2021-01-28 04:58 UTC, xipi2048 requested changes
Testing this feature....

Can you use glTF instead of dae?

2021-01-28 04:58 UTC, xipi2048 commented
this forum looks fucking badass lol

2021-01-29 02:51 UTC, Toadboyf commented
This is updated.

2021-01-29 03:07 UTC, xipi2048 approved these changes

2021-01-29 03:09 UTC, merged